server:
  port: 8080
spring:
  application:
    name: game-shop-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    bootstrap:
      enabled: false
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=0
        - id: product-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/api/products/**,/api/categories/**
          filters:
            - StripPrefix=0
        - id: shop-service
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/api/shops/**
          filters:
            - StripPrefix=0
        - id: order-service
          uri: http://127.0.0.1:8084
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0
        - id: payment-service
          uri: http://127.0.0.1:8085
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=0
        - id: system-service
          uri: http://127.0.0.1:8086
          predicates:
            - Path=/api/announcements/**,/api/files/**,/api/ai/**,/api/py/**
          filters:
            - StripPrefix=0
        - id: uploads-static
          uri: http://127.0.0.1:8086
          predicates:
            - Path=/uploads/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
logging:
  level:
    org.springframework.cloud.gateway: INFO
